# Generated by Django 2.0.7 on 2018-08-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20180818_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='album',
            name='genre',
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(default=4, max_length=250),
            preserve_default=False,
        ),
    ]
